def print_art():
	print("     _")
	print("   _| |")
	print(" _| | |")
	print("| | | |")
	print("| | | | __")
	print("| | | |/  \\")
	print("|       /\\ \\")
	print("|      /  \/")
	print("|      \\  /\\")
	print("|       \/ /")
	print(" \\        /")
	print("  |     /")
	print("  |    | ")
